In [ ]:
import pandas as pd

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

print('Train Shape : ', train.shape)
print('Test Shape : ', test.shape)

train.head()

Train Shape :  (1460, 81)
Test Shape :  (1459, 80)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
X = train.drop("SalePrice", axis=1)
y = train["SalePrice"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (1460, 80)
Target shape: (1460,)

In [ ]:
X = X.select_dtypes(exclude=['object'])
test = test.select_dtypes(exclude=['object'])

print("Numeric features:", X.shape)

Numeric features: (1460, 37)

In [ ]:
X = X.fillna(X.mean())
test = test.fillna(test.mean())

print("Missing values handled!")

Missing values handled!

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

preds = model.predict(X_val)
rmse = np.sqrt(mean_squared_error(y_val, preds))

print("RMSE:", rmse)

RMSE: 36872.90950907531

In [ ]:
test_predictions = model.predict(test)

In [ ]:
submission = pd.DataFrame({
    "Id": test["Id"],
    "SalePrice": test_predictions
})

submission.to_csv("submission.csv", index=False)
submission.head()

     Id      SalePrice
0  1461  114242.395064
1  1462  145991.326110
2  1463  171272.274373
3  1464  196910.350715
4  1465  195900.925095